- name: create pet-clinic user and install jdk         
  hosts: localhost                                 
  roles:
    - role: roles/jdk-script


- name: install required packages
  become: true
  become_method: su
  become_user: pet-clinic
  become_flags: '--login'    
  hosts: localhost
  environment:
      JAVA_HOME: "/home/pet-clinic/jdk-22.0.1"                             
  roles:
    - role: roles/tomcat
    - role: roles/jenkins
    #- role: roles/nagios