- name: install jenkins war file
  get_url:
    url: https://get.jenkins.io/war/2.456/jenkins.war
    dest: /home/pet-clinic
    # force: yes     ... overwite the existing one


# - name: run jenkins 
#   command: /home/pet-clinic/jdk-22.0.1/bin/java -jar /home/pet-clinic/jenkins.war --enable-future-java

- name: copy jenkins.service
  copy:
    src: jenkins.service
    dest: /etc/systemd/system/jenkins.service 


- name: Restart jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes   