- name: install tomcat
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.23/bin/apache-tomcat-10.1.23.tar.gz
    dest: /home/pet-clinic


- name: extract tomcat 
  unarchive:
    src: /home/pet-clinic/apache-tomcat-10.1.23.tar.gz
    dest: /home/pet-clinic/
    remote_src: yes


# - name: know which user login now
#   command: id
#   register: id


# - name: show output for id command
#   debug:
#         msg: "{{ id.stdout }}"


# - name: know the currnt path
#   command: pwd
#   register: current_path


# - name: show output for pwd command
#   debug:
#         msg: "{{ current_path.stdout }}"


# - name: know the contents in pet-clinic home
#   command: ls
#   register: contents


# - name: show output for ls command
#   debug:
#         msg: "{{ contents.stdout }}"


- name: make application running on port 9090
  lineinfile:
        path: /home/pet-clinic/apache-tomcat-10.1.23/conf/server.xml
        regexp: '<Connector port="8080"'
        line: '<Connector port="9090"'


- name: configure tomcat to have access to its manager
  lineinfile:
        path: /home/pet-clinic/apache-tomcat-10.1.23/conf/tomcat-users.xml 
        insertbefore: '</tomcat-users>'
        line: '<role rolename="manager-gui"/> <user username="tomcat" password="password" roles="manager-gui"/>'


- name: stop tomcat
  shell: /home/pet-clinic/apache-tomcat-10.1.23/bin/shutdown.sh


- name: start tomcat
  shell: /home/pet-clinic/apache-tomcat-10.1.23/bin/startup.sh